name: mobi_c
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  animations: ^2.0.11
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_simple_calculator: ^2.3.0
  flutter_slidable: ^3.1.0
  ftpconnect: ^2.0.7
  get_it: ^7.7.0
  http: ^1.2.1
  intl: ^0.19.0
  objectbox: ^2.0.0
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.3
  pool: ^1.5.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  formz: ^0.7.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flow_builder: ^0.1.0
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: any



flutter:
  assets:
    - assets/icons/
  uses-material-design: true
