// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3-02ldNdupIdgfExmBwEYe4owjtnyhw',
    appId: '1:659393448514:web:9c524e2b174e2efeadfbdb',
    messagingSenderId: '659393448514',
    projectId: 'mobicusers',
    authDomain: 'mobicusers.firebaseapp.com',
    storageBucket: 'mobicusers.appspot.com',
    measurementId: 'G-484432PCGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLgUGHocw2nTIV56Olc-hxL9fjE3o7ljk',
    appId: '1:659393448514:android:39f87fd9966efbecadfbdb',
    messagingSenderId: '659393448514',
    projectId: 'mobicusers',
    storageBucket: 'mobicusers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEd1YMIgxDUoBx049Fl8pN8HfqtFe_GKY',
    appId: '1:659393448514:ios:3bf6a2bfdf641bcdadfbdb',
    messagingSenderId: '659393448514',
    projectId: 'mobicusers',
    storageBucket: 'mobicusers.appspot.com',
    iosBundleId: 'com.example.mobic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEd1YMIgxDUoBx049Fl8pN8HfqtFe_GKY',
    appId: '1:659393448514:ios:3bf6a2bfdf641bcdadfbdb',
    messagingSenderId: '659393448514',
    projectId: 'mobicusers',
    storageBucket: 'mobicusers.appspot.com',
    iosBundleId: 'com.example.mobic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU3-02ldNdupIdgfExmBwEYe4owjtnyhw',
    appId: '1:659393448514:web:30e440c696861288adfbdb',
    messagingSenderId: '659393448514',
    projectId: 'mobicusers',
    authDomain: 'mobicusers.firebaseapp.com',
    storageBucket: 'mobicusers.appspot.com',
    measurementId: 'G-6YR7QB1H62',
  );
}
